Multiple iterations of flaky IT

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -70,13 +70,92 @@ stages:
 
 jobs:
   include:
+    - &test_processing_module
+      name: "(openjdk8) processing module test"
+      stage: Tests - phase 1
+      env:
+      - MAVEN_PROJECTS='processing'
+      before_script:
+        - export DRUID_USE_DEFAULT_VALUE_FOR_NULL=true
+      script:
+        - unset _JAVA_OPTIONS
+        # Set MAVEN_OPTS for Surefire launcher. Skip remoteresources to avoid intermittent connection timeouts when
+        # resolving the SIGAR dependency.
+        - >
+          MAVEN_OPTS='-Xmx2048m' ${MVN} test -pl ${MAVEN_PROJECTS}
+          ${MAVEN_SKIP} -Dremoteresources.skip=true -Ddruid.generic.useDefaultValueForNull=${DRUID_USE_DEFAULT_VALUE_FOR_NULL}
+        - sh -c "dmesg | egrep -i '(oom|out of memory|kill process|killed).*' -C 1 || exit 0"
+        - free -m
+        - ${MVN} -pl ${MAVEN_PROJECTS} jacoco:report
+        # Add merge target branch to determine diff (see https://github.com/travis-ci/travis-ci/issues/6069).
+        # This is not needed for build triggered by tags, since there will be no code diff.
+        - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"  # for debugging
+        - if [[ -z "${TRAVIS_TAG}" ]]; then git remote set-branches --add origin ${TRAVIS_BRANCH} && git fetch; fi
+        # Determine the modified files that match the maven projects being tested. We use maven project lists that
+        # either exclude (starts with "!") or include (does not start with "!"), so both cases need to be handled.
+        # If the build is triggered by a tag, an error will be printed, but `all_files` will be correctly set to empty
+        # so that the coverage check is skipped.
+        - all_files="$(git diff --name-only origin/${TRAVIS_BRANCH}...HEAD | grep "\.java$" || [[ $? == 1 ]])"
+        - for f in ${all_files}; do echo $f; done  # for debugging
+        - >
+          if [[ "${MAVEN_PROJECTS}" = \!* ]]; then
+          regex="${MAVEN_PROJECTS:1}";
+          regex="^${regex//,\!/\\|^}";
+          project_files="$(echo "${all_files}" | grep -v "${regex}" || [[ $? == 1 ]])";
+          else
+          regex="^${MAVEN_PROJECTS//,/\\|^}";
+          project_files="$(echo "${all_files}" | grep "${regex}" || [[ $? == 1 ]])";
+          fi
+        - for f in ${project_files}; do echo $f; done  # for debugging
+        # Check diff code coverage for the maven projects being tested (retry install in case of network error).
+        # Currently, the function coverage check is not reliable, so it is disabled.
+        - >
+          if [ -n "${project_files}" ]; then
+          travis_retry npm install @connectis/diff-test-coverage@1.5.3
+          && git diff origin/${TRAVIS_BRANCH}...HEAD -- ${project_files}
+          | node_modules/.bin/diff-test-coverage
+          --coverage "**/target/site/jacoco/jacoco.xml"
+          --type jacoco
+          --line-coverage 50
+          --branch-coverage 50
+          --function-coverage 0
+          --log-template "coverage-lines-complete"
+          --log-template "coverage-files-complete"
+          --log-template "totals-complete"
+          --log-template "errors"
+          --
+          || { printf "\n\n****FAILED****\nDiff code coverage check failed. To view coverage report, run 'mvn clean test jacoco:report' and open 'target/site/jacoco/index.html'\nFor more details on how to run code coverage locally, follow instructions here - https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md#running-code-coverage-locally\n\n" && false; }
+          fi
+      after_success:
+        # retry in case of network error
+        - travis_retry curl -o codecov.sh -s https://codecov.io/bash
+        - travis_retry bash codecov.sh -X gcov
+
     # Integration tests Java Compile version is set by the machine environment jdk (set by the jdk key)
     # Integration tests Java Runtime version is set by the JVM_RUNTIME env property (set env key to -Djvm.runtime=<JVM_RUNTIME_VERSION>)
     # Integration tests will either use MiddleManagers or Indexers
     # (Currently integration tests only support running with jvm runtime 8 and 11)
     # START - Integration tests for Compile with Java 8 and Run with Java 8
+    - &integration_batch_index
+      name: "(Compile=openjdk8, Run=openjdk8) batch index integration test"
+      stage: Tests - phase 2
+      jdk: openjdk8
+      services: &integration_test_services
+        - docker
+      env: TESTNG_GROUPS='-Dgroups=batch-index' JVM_RUNTIME='-Djvm.runtime=8' USE_INDEXER='middleManager'
+      script: &run_integration_test
+        - ${MVN} verify -pl integration-tests -P integration-tests ${TESTNG_GROUPS} ${JVM_RUNTIME} -Dit.indexer=${USE_INDEXER} ${MAVEN_SKIP} -Doverride.config.path=${OVERRIDE_CONFIG_PATH}
+      after_failure: &integration_test_diags
+        - for v in ~/shared/logs/*.log ; do
+          echo $v logtail ======================== ; tail -100 $v ;
+          done
+        - for v in broker middlemanager overlord router coordinator historical ; do
+          echo $v dmesg ======================== ;
+          docker exec -it druid-$v sh -c 'dmesg | tail -3' ;
+          done
+
     - &integration_kafka_transactional_index
-      name: "(Compile=openjdk8, Run=openjdk8) transactional kafka index integration test 0"
+      name: "(Compile=openjdk8, Run=openjdk8) transactional kafka index integration test"
       stage: Tests - phase 2
       jdk: openjdk8
       services: *integration_test_services
@@ -158,15 +237,6 @@ jobs:
 
     - &integration_kafka_transactional_index
       name: "(Compile=openjdk8, Run=openjdk8) transactional kafka index integration test 9"
-      stage: Tests - phase 2
-      jdk: openjdk8
-      services: *integration_test_services
-      env: TESTNG_GROUPS='-Dgroups=kafka-transactional-index' JVM_RUNTIME='-Djvm.runtime=8' USE_INDEXER='middleManager'
-      script: *run_integration_test
-      after_failure: *integration_test_diags
-
-    - &integration_kafka_transactional_index
-      name: "(Compile=openjdk8, Run=openjdk8) transactional kafka index integration test 10"
       stage: Tests - phase 2
       jdk: openjdk8
       services: *integration_test_services
@@ -263,7 +333,21 @@ jobs:
       env: TESTNG_GROUPS='-Dgroups=query' JVM_RUNTIME='-Djvm.runtime=11' USE_INDEXER='middleManager' MYSQL_DRIVER_CLASSNAME='org.mariadb.jdbc.Driver' OVERRIDE_CONFIG_PATH='./environment-configs/test-groups/prepopulated-data'
 
     # END - Integration tests for Compile with Java 8 and Run with Java 11
-    
+
+    - &integration_batch_index_k8s
+      name: "(Compile=openjdk8, Run=openjdk8, Cluster Build On K8s) ITNestedQueryPushDownTest integration test"
+      stage: Tests - phase 2
+      jdk: openjdk8
+      services: &integration_test_services_k8s
+        - docker
+      env: CONFIG_FILE='k8s_run_config_file.json' IT_TEST='-Dit.test=ITNestedQueryPushDownTest' POD_NAME=int-test POD_NAMESPACE=default BUILD_DRUID_CLSUTER=true
+      script: &run_integration_test_k8s
+        - ${MVN} verify -pl integration-tests -P int-tests-config-file ${IT_TEST} ${MAVEN_SKIP} -Dpod.name=${POD_NAME} -Dpod.namespace=${POD_NAMESPACE} -Dbuild.druid.cluster=${BUILD_DRUID_CLSUTER}
+      after_failure: &integration_test_diags_k8s
+        - for v in broker middlemanager router coordinator historical ; do
+          echo "------------------------druid-tiny-cluster-"$v"s-0-------------------------";
+          sudo /usr/local/bin/kubectl logs --tail 1000 druid-tiny-cluster-"$v"s-0;
+          done
     - &security_vulnerabilities
       name: "security vulnerabilities"
       stage: cron
