enable pr build

diff --git a/screwdriver.yaml b/screwdriver.yaml
--- a/screwdriver.yaml
+++ b/screwdriver.yaml
@@ -18,6 +18,11 @@ shared:
     DRUID_PKG_NAME: "druid_dev"
     DRUID_INABOX_PKG_NAME: "druid_inabox_dev"
     HDFS_BASE_DIR: "metamx_greyhawk_ci_0_7"
+    HOST_LIST: "druid-vm003.us.bf1.yahoo.com druid-vm004.us.bf1.yahoo.com druid-vm005.us.bf1.yahoo.com druid-vm006.us.bf1.yahoo.com druid-vm007.us.bf1.yahoo.com"
+    MARKER_DIR: "being_used_by_pr_build"
+    BUILD_INFO_MARKER_FILE: "build_info"
+    # The file that stores the hostname where screwdriver runs tests. This is generated by druid_package/screwdriver/find_host.sh
+    PR_HOST_FILE: "pr_host"
 
   build_containers: [oracle-jdk8-current]
 
@@ -33,11 +38,109 @@ shared:
     druid_code_build:
       description: create druid code jars
       command: mvn install
+    compute_druid_version:
+      description: compute the hash for druid version
+      command: >
+        echo $(fgrep '<version>' pom.xml | sed -n 2p | grep -oP '\d+\.\d+\.\d+')-$(date '+%s')-$(git rev-parse --short HEAD)-${BUILD_NUMBER} > druid.version &&
+        if [ ! -s druid.version ]; then echo 'Error: druid.version is empty!' && exit 1; else echo "druid.version is `cat druid.version`"; fi || exit $?
+    set_druid_version:
+      description: set druid jars version
+      command: mvn org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion="`cat druid.version`"
+    clone_druid_pkg:
+      description: clone druid package
+      command: git clone git@git.corp.yahoo.com:greyhawk/druid_package.git
+    set_config_files:
+      description: call setup_flags_n_vars.sh (comes from druid_package repo) to replace placeholded embedded in the yicf files with meaningful names
+      command: >
+        cd druid_package &&
+        sh ./screwdriver/update_vars.sh ${SD_SETTING_DRUID_PKG_NAME} ${SD_SETTING_DRUID_INABOX_PKG_NAME} ${SD_SETTING_HDFS_BASE_DIR} &&
+        git diff &&
+        git commit -a -m "commit to make yinst_create happy" || exit $?
+    druid_pkg_code_build:
+      description: copy dependencies for druid_package
+      command: mvn -f druid_package/pom.xml -Ddruid.version="`cat druid.version`" install dependency:copy-dependencies
+    show_tree:
+      description: tree under root
+      command: tree .
+    check_druid_jars_version:
+      description: check whether downloaded druid jars have correct version (check_version.sh comes from druid_package repo)
+      command: sh druid_package/screwdriver/check_version.sh "`cat druid.version`" druid_package/ydruid_package/target/dependency
+    clone_ci_tests_pkg:
+      description: clone ci_tests package
+      command: git clone git@git.corp.yahoo.com:greyhawk/ci_tests.git
+    ci_tests_code_build:
+      description: build ci tests and copy its dependencies
+      command: mvn -f ci_tests/pom.xml package dependency:copy-dependencies
+    create_druid_yinst_pkg:
+      description: create the yinst package from druid_packcage
+      command: >
+        cd druid_package &&
+        mkdir yinst_package_druid_dir &&
+        yinst_create -r ydruid_package/druid.yicf --target_dir=yinst_package_druid_dir || exit $?
+    create_druid_inabox_yinst_pkg:
+      description: create the yinst package for druid_inabox
+      command: >
+        cd druid_package &&
+        mkdir yinst_package_druid_inabox_dir &&
+        yinst_create -r druid_inabox/druid_inabox.yicf --target_dir=yinst_package_druid_inabox_dir || exit $?
+    create_ci_tests_yinst_pkg:
+      description: create yinst ci tests package
+      command: >
+        cd ci_tests &&
+        mkdir yinst_package_ci_tests_dir &&
+        yinst_create -r greyhawk_ci_tests.yicf --target_dir=yinst_package_ci_tests_dir || exit $?
+
 jobs:
   pull-request:
+    plugins:
+      test_results:
+        enabled: false
+      coverage:
+        enabled: false
     order:
       - init
+      - compute_druid_version
+      - set_druid_version
       - druid_code_build
+      - clone_druid_pkg
+      - set_config_files
+      - druid_pkg_code_build
+      - show_tree
+      - check_druid_jars_version
+      - clone_ci_tests_pkg
+      - ci_tests_code_build
+      - create_druid_yinst_pkg
+      - create_druid_inabox_yinst_pkg
+      - create_ci_tests_yinst_pkg
+      - find_host
+      - clean_yinst_pkg_pr
+      - scp_druid_yinst_pkg_pr
+      - scp_druid_inabox_pkg_pr
+      - scp_ci_tests_pkg_pr
+      - test_pr_host
+      - remove_marker_on_pr_host
+    steps:
+      find_host:
+        description: find the host to run tests for the PR
+        command: sh druid_package/screwdriver/find_host.sh ${SD_SETTING_HOST_LIST}
+      clean_yinst_pkg_pr:
+        description: clean up yinst packages stored on pull request test machine
+        command: ssh ${SD_SETTING_SSH_OPTIONS} `cat ${SD_SETTING_PR_HOST_FILE}` "rm -f *.tgz"
+      scp_druid_yinst_pkg_pr:
+        description: scp yinst test package to pull request test machine
+        command: scp ${SD_SETTING_SSH_OPTIONS} druid_package/yinst_package_druid_dir/*.tgz `cat ${SD_SETTING_PR_HOST_FILE}`:~
+      scp_druid_inabox_pkg_pr:
+        description: scp druid_inabox test package to pull request test machine
+        command: scp ${SD_SETTING_SSH_OPTIONS} druid_package/yinst_package_druid_inabox_dir/*.tgz `cat ${SD_SETTING_PR_HOST_FILE}`:~
+      scp_ci_tests_pkg_pr:
+        description: scp ci_tests package to pull request test machine
+        command: scp ${SD_SETTING_SSH_OPTIONS} ci_tests/yinst_package_ci_tests_dir/*.tgz `cat ${SD_SETTING_PR_HOST_FILE}`:~
+      test_pr_host:
+        description: run ci_tests on pull request host
+        command: sh druid_package/ci_tests_runner/bin/run_ci_tests.sh `cat ${SD_SETTING_PR_HOST_FILE}` smoke
+      remove_marker_on_pr_host:
+        description: remove host marker on pr host
+        command: ssh ${SD_SETTING_SSH_OPTIONS} `cat ${SD_SETTING_PR_HOST_FILE}` "rm -rf ${SD_SETTING_MARKER_DIR}"
   component:
     order:
       - init
@@ -68,57 +171,6 @@ jobs:
       - publish_druid_yinst_pkg
       - publish_druid_inabox_yinst_pkg
     steps:
-      compute_druid_version:
-        description: compute the hash for druid version
-        command: >
-          echo $(fgrep '<version>' pom.xml | sed -n 2p | grep -oP '\d+\.\d+\.\d+')-$(date '+%s')-$(git rev-parse --short HEAD)-${BUILD_NUMBER} > druid.version &&
-          if [ ! -s druid.version ]; then echo 'Error: druid.version is empty!' && exit 1; else echo "druid.version is `cat druid.version`"; fi || exit $?
-      set_druid_version:
-        description: set druid jars version
-        command: mvn org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion="`cat druid.version`"
-      clone_druid_pkg:
-        description: clone druid package
-        command: git clone git@git.corp.yahoo.com:greyhawk/druid_package.git
-      set_config_files:
-        description: call setup_flags_n_vars.sh (comes from druid_package repo) to replace placeholded embedded in the yicf files with meaningful names
-        command: >
-          cd druid_package &&
-          sh ./screwdriver/update_vars.sh ${SD_SETTING_DRUID_PKG_NAME} ${SD_SETTING_DRUID_INABOX_PKG_NAME} ${SD_SETTING_HDFS_BASE_DIR} &&
-          git diff &&
-          git commit -a -m "commit to make yinst_create happy" || exit $?
-      druid_pkg_code_build:
-        description: copy dependencies for druid_package
-        command: mvn -f druid_package/pom.xml -Ddruid.version="`cat druid.version`" install dependency:copy-dependencies
-      show_tree:
-        description: tree under root
-        command: tree .
-      check_druid_jars_version:
-        description: check whether downloaded druid jars have correct version (check_version.sh comes from druid_package repo)
-        command: sh druid_package/screwdriver/check_version.sh "`cat druid.version`" druid_package/ydruid_package/target/dependency
-      clone_ci_tests_pkg:
-        description: clone ci_tests package
-        command: git clone git@git.corp.yahoo.com:greyhawk/ci_tests.git
-      ci_tests_code_build:
-        description: build ci tests and copy its dependencies
-        command: mvn -f ci_tests/pom.xml package dependency:copy-dependencies
-      create_druid_yinst_pkg:
-        description: create the yinst package from druid_packcage
-        command: >
-          cd druid_package &&
-          mkdir yinst_package_druid_dir &&
-          yinst_create -r ydruid_package/druid.yicf --target_dir=yinst_package_druid_dir || exit $?
-      create_druid_inabox_yinst_pkg:
-        description: create the yinst package for druid_inabox
-        command: >
-          cd druid_package &&
-          mkdir yinst_package_druid_inabox_dir &&
-          yinst_create -r druid_inabox/druid_inabox.yicf --target_dir=yinst_package_druid_inabox_dir || exit $?
-      create_ci_tests_yinst_pkg:
-        description: create yinst ci tests package
-        command: >
-          cd ci_tests &&
-          mkdir yinst_package_ci_tests_dir &&
-          yinst_create -r greyhawk_ci_tests.yicf --target_dir=yinst_package_ci_tests_dir || exit $?
       clean_yinst_pkg_smoke:
         description: clean up yinst packages stored on smoke test machine
         command: ssh ${SD_SETTING_SSH_OPTIONS} ${SD_SETTING_SMOKE_HOST} "rm -f *.tgz"
