Update fn names and clean up code

diff --git a/examples/bin/run-druid b/examples/bin/run-druid
--- a/examples/bin/run-druid
+++ b/examples/bin/run-druid
@@ -17,9 +17,9 @@
 # specific language governing permissions and limitations
 # under the License.
 
-if [ "$#" -gt 2 ] || [ "$#" == 0 ]
+if [ "$#" -gt 2 ] || [ "$#" -eq 0 ]
 then
-  echo "usage: $0 <service> [conf-dir]" >&2
+  >&2 echo "usage: $0 <service> [conf-dir]" >&2
   exit 1
 fi
 
@@ -36,9 +36,9 @@ fi
 
 CONFDIR="$(cd "$CONFDIR" && pwd)"
 WHEREAMI="$(cd "$WHEREAMI" && pwd)"
-JAVA_BIN=`source "$WHEREAMI"/java-util && get_java_bin`
+JAVA_BIN="$(source "$WHEREAMI"/java-util && get_java_bin_dir)"
 if [ -z "$JAVA_BIN" ]; then
-  echo "Could not find java - please run $WHEREAMI/verify-java to confirm it is installed."
+  >&2 echo "Could not find java - please run $WHEREAMI/verify-java to confirm it is installed."
   exit 1
 fi
 cd "$WHEREAMI/.."
diff --git a/examples/bin/run-zk b/examples/bin/run-zk
--- a/examples/bin/run-zk
+++ b/examples/bin/run-zk
@@ -19,7 +19,7 @@
 
 if [ "$#" -gt 1 ]
 then
-  echo "usage: $0 [conf-dir]" >&2
+  >&2 echo "usage: $0 [conf-dir]" >&2
   exit 1
 fi
 
@@ -35,9 +35,9 @@ fi
 
 CONFDIR="$(cd "$CONFDIR" && pwd)/zk"
 WHEREAMI="$(cd "$WHEREAMI" && pwd)"
-JAVA_BIN=`source "$WHEREAMI"/java-util && get_java_bin`
+JAVA_BIN="$(source "$WHEREAMI"/java-util && get_java_bin_dir)"
 if [ -z "$JAVA_BIN" ]; then
-  echo "Could not find java - please run $WHEREAMI/verify-java to confirm it is installed."
+  >&2 echo "Could not find java - please run $WHEREAMI/verify-java to confirm it is installed."
   exit 1
 fi
 
