Allow startup scripts to specify java home
The startup scripts now look for java in 3 locations. The order is from
most related to druid to least, ie
    ${DRUID_JAVA_HOME}
    ${JAVA_HOME}
    ${PATH}

diff --git a/examples/bin/run-druid b/examples/bin/run-druid
--- a/examples/bin/run-druid
+++ b/examples/bin/run-druid
@@ -17,7 +17,7 @@
 # specific language governing permissions and limitations
 # under the License.
 
-if [ "$#" -gt 2 ]
+if [ "$#" -gt 2 ] || [ "$#" == 0 ]
 then
   echo "usage: $0 <service> [conf-dir]" >&2
   exit 1
@@ -36,8 +36,12 @@ fi
 
 CONFDIR="$(cd "$CONFDIR" && pwd)"
 WHEREAMI="$(cd "$WHEREAMI" && pwd)"
-
+JAVA_BIN=`source "$WHEREAMI"/java-util && get_java_bin`
+if [ -z "$JAVA_BIN" ]; then
+  echo "Could not find java - please run $WHEREAMI/verify-java to confirm it is installed."
+  exit 1
+fi
 cd "$WHEREAMI/.."
-exec java `cat "$CONFDIR"/"$WHATAMI"/jvm.config | xargs` \
+exec "$JAVA_BIN"/java `cat "$CONFDIR"/"$WHATAMI"/jvm.config | xargs` \
   -cp "$CONFDIR"/"$WHATAMI":"$CONFDIR"/_common:"$CONFDIR"/_common/hadoop-xml:"$CONFDIR"/../_common:"$CONFDIR"/../_common/hadoop-xml:"$WHEREAMI/../lib/*" \
   `cat "$CONFDIR"/$WHATAMI/main.config | xargs`
diff --git a/examples/bin/run-zk b/examples/bin/run-zk
--- a/examples/bin/run-zk
+++ b/examples/bin/run-zk
@@ -35,9 +35,14 @@ fi
 
 CONFDIR="$(cd "$CONFDIR" && pwd)/zk"
 WHEREAMI="$(cd "$WHEREAMI" && pwd)"
+JAVA_BIN=`source "$WHEREAMI"/java-util && get_java_bin`
+if [ -z "$JAVA_BIN" ]; then
+  echo "Could not find java - please run $WHEREAMI/verify-java to confirm it is installed."
+  exit 1
+fi
 
 cd "$WHEREAMI/.."
-exec java `cat "$CONFDIR"/jvm.config | xargs` \
+exec "$JAVA_BIN"/java `cat "$CONFDIR"/jvm.config | xargs` \
   -cp "$WHEREAMI/../lib/*:$CONFDIR" \
   -Dzookeeper.jmx.log4j.disable=true \
   org.apache.zookeeper.server.quorum.QuorumPeerMain \
